/*----------------------------------------------------------------------------------------------+
|                                                                                               |
|     This code was generated by the ModBotWebistieAPICodeGenerator, do not change it directly  |
|                                                                                               |
| /---------------------------------------------------------------------------------------------+
| |
| | Operation Options:
| |
| |	OperationID: deleteComment
| |	Arguments: [targetModId, targetCommentId]
| |	ArgumentsInQuerystring: False
| |	HideInAPI: False
| |	MinimumAuthenticationLevelToCall: BasicUser
| |	ParseAsJson: True
| |
\*/

using System;
using System.Collections;

namespace ModBotWebsiteAPI
{
    public static partial class API
    {
        public static void DeleteComment(string targetModId, string targetCommentId, Action<JsonObject> callback)
        {
            StaticCoroutineRunner.StartStaticCoroutine(_deleteComment(targetModId, targetCommentId, callback));
        }

        private static IEnumerator _deleteComment(string targetModId, string targetCommentId, Action<JsonObject> callback)
        {

            string url = MODBOT_API_URL_BASE;
            string data = "";

            url += "deleteComment";
            JsonConstructor json = new JsonConstructor();
            json.AppendValue("targetModId", targetModId);
            json.AppendValue("targetCommentId", targetCommentId);
            data = json.ToString();

            yield return SendRequest(url, data, callback);
        }
    }
}
