/*----------------------------------------------------------------------------------------------+
|                                                                                               |
|     This code was generated by the ModBotWebistieAPICodeGenerator, do not change it directly  |
|                                                                                               |
| /---------------------------------------------------------------------------------------------+
| |
| | Operation Options:
| |
| |	OperationID: downloadMod
| |	Arguments: [id]
| |	ArgumentsInQuerystring: False
| |	HideInAPI: False
| |	MinimumAuthenticationLevelToCall: None
| |	ParseAsJson: False
| |
\*/

using System;
using System.Collections;

namespace ModBotWebsiteAPI
{
    public static partial class API
    {
        public static void DownloadMod(string id, Action<string> callback)
        {
            StaticCoroutineRunner.StartStaticCoroutine(_downloadMod(id, callback));
        }

        private static IEnumerator _downloadMod(string id, Action<string> callback)
        {

            string url = MODBOT_API_URL_BASE;
            string data = "";

            url += "downloadMod";
            JsonConstructor json = new JsonConstructor();
            json.AppendValue("id", id);
            data = json.ToString();

            yield return SendRequest(url, data, callback);
        }
    }
}
