/*----------------------------------------------------------------------------------------------+
|                                                                                               |
|     This code was generated by the ModBotWebistieAPICodeGenerator, do not change it directly  |
|                                                                                               |
| /---------------------------------------------------------------------------------------------+
| |
| | Operation Options:
| |
| |	OperationID: getModImage
| |	Arguments: [element, id]
| |	ArgumentsInQuerystring: True
| |	HideInAPI: False
| |	MinimumAuthenticationLevelToCall: None
| |	ParseAsJson: False
| |
\*/

using System;
using System.Collections;

namespace ModBotWebsiteAPI
{
    public static partial class API
    {
        public static void GetModImage(string element, string id, Action<string> callback)
        {
            StaticCoroutineRunner.StartStaticCoroutine(_getModImage(element, id, callback));
        }

        private static IEnumerator _getModImage(string element, string id, Action<string> callback)
        {

            string url = MODBOT_API_URL_BASE;
            string data = "";

            url += "getModImage&element=" + element + "&id=" + id;
            data = "{}";


            yield return SendRequest(url, data, callback);
        }
    }
}
