/*----------------------------------------------------------------------------------------------+
|                                                                                               |
|     This code was generated by the ModBotWebistieAPICodeGenerator, do not change it directly  |
|                                                                                               |
| /---------------------------------------------------------------------------------------------+
| |
| | Operation Options:
| |
| |	OperationID: getPlayerPrefix
| |	Arguments: [playfabID]
| |	ArgumentsInQuerystring: True
| |	HideInAPI: False
| |	MinimumAuthenticationLevelToCall: None
| |	ParseAsJson: True
| |
\*/

using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace ModBotWebsiteAPI
{
    public static partial class API
    {
        public static void GetPlayerPrefix(string playfabID, Action<JsonObject> callback) {
            StaticCoroutineRunner.StartStaticCoroutine(_getPlayerPrefix(playfabID, callback));
        }

        private static IEnumerator _getPlayerPrefix(string playfabID, Action<JsonObject> callback) {
            
            string url = MODBOT_API_URL_BASE;
            string data = "";

            url += "getPlayerPrefix&playfabID=" + playfabID;
			data = "{}";


            yield return SendRequest(url, data, callback);
        }
    }
}
