/*----------------------------------------------------------------------------------------------+
|                                                                                               |
|     This code was generated by the ModBotWebistieAPICodeGenerator, do not change it directly  |
|                                                                                               |
| /---------------------------------------------------------------------------------------------+
| |
| | Operation Options:
| |
| |	OperationID: getUserHeader
| |	Arguments: [element, userID]
| |	ArgumentsInQuerystring: True
| |	HideInAPI: False
| |	MinimumAuthenticationLevelToCall: None
| |	ParseAsJson: False
| |
\*/

using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace ModBotWebsiteAPI
{
    public static partial class API
    {
        public static void GetUserHeader(string element, string userID, Action<string> callback) {
            StaticCoroutineRunner.StartStaticCoroutine(_getUserHeader(element, userID, callback));
        }

        private static IEnumerator _getUserHeader(string element, string userID, Action<string> callback) {
            
            string url = MODBOT_API_URL_BASE;
            string data = "";

            url += "getUserHeader&element=" + element + "&userID=" + userID;
			data = "{}";


            yield return SendRequest(url, data, callback);
        }
    }
}
