/*----------------------------------------------------------------------------------------------+
|                                                                                               |
|     This code was generated by the ModBotWebistieAPICodeGenerator, do not change it directly  |
|                                                                                               |
| /---------------------------------------------------------------------------------------------+
| |
| | Operation Options:
| |
| |	OperationID: hasLiked
| |	Arguments: [modId]
| |	ArgumentsInQuerystring: False
| |	HideInAPI: False
| |	MinimumAuthenticationLevelToCall: BasicUser
| |	ParseAsJson: True
| |
\*/

using System;
using System.Collections;

namespace ModBotWebsiteAPI
{
    public static partial class API
    {
        public static void HasLiked(string modId, Action<JsonObject> callback)
        {
            StaticCoroutineRunner.StartStaticCoroutine(_hasLiked(modId, callback));
        }

        private static IEnumerator _hasLiked(string modId, Action<JsonObject> callback)
        {

            string url = MODBOT_API_URL_BASE;
            string data = "";

            url += "hasLiked";
            JsonConstructor json = new JsonConstructor();
            json.AppendValue("modId", modId);
            data = json.ToString();

            yield return SendRequest(url, data, callback);
        }
    }
}
