/*----------------------------------------------------------------------------------------------+
|                                                                                               |
|     This code was generated by the ModBotWebistieAPICodeGenerator, do not change it directly  |
|                                                                                               |
| /---------------------------------------------------------------------------------------------+
| |
| | Operation Options:
| |
| |	OperationID: isValidSession
| |	Arguments: [sessionId]
| |	ArgumentsInQuerystring: False
| |	HideInAPI: False
| |	MinimumAuthenticationLevelToCall: None
| |	ParseAsJson: False
| |
\*/

using System;
using System.Collections;

namespace ModBotWebsiteAPI
{
    public static partial class API
    {
        public static void IsValidSession(string sessionId, Action<string> callback)
        {
            StaticCoroutineRunner.StartStaticCoroutine(_isValidSession(sessionId, callback));
        }

        private static IEnumerator _isValidSession(string sessionId, Action<string> callback)
        {

            string url = MODBOT_API_URL_BASE;
            string data = "";

            url += "isValidSession";
            JsonConstructor json = new JsonConstructor();
            json.AppendValue("sessionId", sessionId);
            data = json.ToString();

            yield return SendRequest(url, data, callback);
        }
    }
}
