/*----------------------------------------------------------------------------------------------+
|                                                                                               |
|     This code was generated by the ModBotWebistieAPICodeGenerator, do not change it directly  |
|                                                                                               |
| /---------------------------------------------------------------------------------------------+
| |
| | Operation Options:
| |
| |	OperationID: setCustomConsoleCss
| |	Arguments: [css]
| |	ArgumentsInQuerystring: False
| |	HideInAPI: False
| |	MinimumAuthenticationLevelToCall: Admin
| |	ParseAsJson: False
| |
\*/

using System;
using System.Collections;

namespace ModBotWebsiteAPI
{
    public static partial class API
    {
        public static void SetCustomConsoleCss(string css, Action<string> callback)
        {
            StaticCoroutineRunner.StartStaticCoroutine(_setCustomConsoleCss(css, callback));
        }

        private static IEnumerator _setCustomConsoleCss(string css, Action<string> callback)
        {

            string url = MODBOT_API_URL_BASE;
            string data = "";

            url += "setCustomConsoleCss";
            JsonConstructor json = new JsonConstructor();
            json.AppendValue("css", css);
            data = json.ToString();

            yield return SendRequest(url, data, callback);
        }
    }
}
