/*----------------------------------------------------------------------------------------------+
|                                                                                               |
|     This code was generated by the ModBotWebistieAPICodeGenerator, do not change it directly  |
|                                                                                               |
| /---------------------------------------------------------------------------------------------+
| |
| | Operation Options:
| |
| |	OperationID: setPlayerTags
| |	Arguments: [tags]
| |	ArgumentsInQuerystring: False
| |	HideInAPI: False
| |	MinimumAuthenticationLevelToCall: BasicUser
| |	ParseAsJson: True
| |
\*/

using System;
using System.Collections;

namespace ModBotWebsiteAPI
{
    public static partial class API
    {
        public static void SetPlayerTags(string tags, Action<JsonObject> callback)
        {
            StaticCoroutineRunner.StartStaticCoroutine(_setPlayerTags(tags, callback));
        }

        private static IEnumerator _setPlayerTags(string tags, Action<JsonObject> callback)
        {

            string url = MODBOT_API_URL_BASE;
            string data = "";

            url += "setPlayerTags";
            JsonConstructor json = new JsonConstructor();
            json.AppendValue("tags", tags);
            data = json.ToString();

            yield return SendRequest(url, data, callback);
        }
    }
}
