/*----------------------------------------------------------------------------------------------+
|                                                                                               |
|     This code was generated by the ModBotWebistieAPICodeGenerator, do not change it directly  |
|                                                                                               |
| /---------------------------------------------------------------------------------------------+
| |
| | Operation Options:
| |
| |	OperationID: signInFromGame
| |	Arguments: [username, password, playfabID]
| |	ArgumentsInQuerystring: False
| |	HideInAPI: False
| |	MinimumAuthenticationLevelToCall: None
| |	ParseAsJson: True
| |
\*/

using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace ModBotWebsiteAPI
{
    public static partial class API
    {
        public static void SignInFromGame(string username, string password, string playfabID, Action<JsonObject> callback) {
            StaticCoroutineRunner.StartStaticCoroutine(_signInFromGame(username, password, playfabID, callback));
        }

        private static IEnumerator _signInFromGame(string username, string password, string playfabID, Action<JsonObject> callback) {
            
            string url = MODBOT_API_URL_BASE;
            string data = "";

            url += "signInFromGame";
			JsonConstructor json = new JsonConstructor();
			json.AppendValue("username", username);
			json.AppendValue("password", password);
			json.AppendValue("playfabID", playfabID);
			data = json.ToString();

            yield return SendRequest(url, data, callback);
        }
    }
}
