/*----------------------------------------------------------------------------------------------+
|                                                                                               |
|     This code was generated by the ModBotWebistieAPICodeGenerator, do not change it directly  |
|                                                                                               |
| /---------------------------------------------------------------------------------------------+
| |
| | Operation Options:
| |
| |	OperationID: uploadProfilePicture
| |	Arguments: []
| |	ArgumentsInQuerystring: False
| |	HideInAPI: True
| |	MinimumAuthenticationLevelToCall: BasicUser
| |	ParseAsJson: False
| |
\*/

//This operation is not included in the API becuase HideInAPI was set to true