/*----------------------------------------------------------------------------------------------+
|                                                                                               |
|     This code was generated by the ModBotWebistieAPICodeGenerator, do not change it directly  |
|                                                                                               |
| /---------------------------------------------------------------------------------------------+
| |
| | Operation Options:
| |
| |	OperationID: uploadTag
| |	Arguments: [tagName, tagBody]
| |	ArgumentsInQuerystring: False
| |	HideInAPI: False
| |	MinimumAuthenticationLevelToCall: BasicUser
| |	ParseAsJson: True
| |
\*/

using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace ModBotWebsiteAPI
{
    public static partial class API
    {
        public static void UploadTag(string tagName, string tagBody, Action<JsonObject> callback) {
            StaticCoroutineRunner.StartStaticCoroutine(_uploadTag(tagName, tagBody, callback));
        }

        private static IEnumerator _uploadTag(string tagName, string tagBody, Action<JsonObject> callback) {
            
            string url = MODBOT_API_URL_BASE;
            string data = "";

            url += "uploadTag";
			JsonConstructor json = new JsonConstructor();
			json.AppendValue("tagName", tagName);
			json.AppendValue("tagBody", tagBody);
			data = json.ToString();

            yield return SendRequest(url, data, callback);
        }
    }
}
